---

- name: Maintainance Tesks on SCOM
  hosts: scom
  gather_facts: True

  tasks:

   - name: Get SCOM CU version
     win_file_version:
        path: 'C:\Program Files\Microsoft System Center 2016\Operations Manager\Server\Microsoft.EnterpriseManagement.RuntimeService.dll'
     register: exe_file_version 

   - debug: msg="{{exe_file_version}}"
...

