---

- name: Maintainance Tesks on SCOM
  hosts: scom
  gather_facts: True

  tasks:

   - name: Get SP version
     win_updates: category_names=['SecurityUpdates','CriticalUpdates','UpdateRollups'] state=searched log_path=c:/ansible_wu.txt
        
     register: check_win_updates 

   - debug: msg="{{check_win_updates}}"
...

